//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wwfd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contributor
    {
        public Contributor()
        {
            this.QuoteFlags = new HashSet<QuoteFlag>();
            this.Quotes = new HashSet<Quote>();
        }
    
        public System.Guid ContributorID { get; set; }
        public byte RoleID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
        public string FullName { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<QuoteFlag> QuoteFlags { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
