//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wwfd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeywordPhras
    {
        public int KeywordPhraseID { get; set; }
        public string Phrase { get; set; }
        public short Cardinality { get; set; }
        public decimal Ratio { get; set; }
    }
}
