//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wwfd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QOTD
    {
        public int ID { get; set; }
        public int QuoteID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Status { get; set; }
    }
}
