//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wwfd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QOTDSubscriber
    {
        public string SubscriberID { get; set; }
        public string SubscriberEmail { get; set; }
        public bool Active { get; set; }
        public System.DateTime DateAdded { get; set; }
    }
}
