//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wwfd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteHistory
    {
        public int HistoryID { get; set; }
        public int QuoteID { get; set; }
        public int ContributorID { get; set; }
        public string Description { get; set; }
    
        public virtual Quote Quote { get; set; }
    }
}
