//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wwfd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteFlagType
    {
        public QuoteFlagType()
        {
            this.QuoteFlags = new HashSet<QuoteFlag>();
        }
    
        public string QuoteFlagTypeID { get; set; }
        public string FlagDescription { get; set; }
    
        public virtual ICollection<QuoteFlag> QuoteFlags { get; set; }
    }
}
