//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wwfd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteTaskType
    {
        public QuoteTaskType()
        {
            this.QuoteTaskHistories = new HashSet<QuoteTaskHistory>();
        }
    
        public int QuoteTaskTypeID { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
    
        public virtual ICollection<QuoteTaskHistory> QuoteTaskHistories { get; set; }
    }
}
