//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wwfd.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WwfdEntities : DbContext
    {
        public WwfdEntities()
            : base("name=WwfdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contributor> Contributors { get; set; }
        public virtual DbSet<Founder> Founders { get; set; }
        public virtual DbSet<KeywordPhras> KeywordPhrases { get; set; }
        public virtual DbSet<QOTD> QOTDs { get; set; }
        public virtual DbSet<QOTDSubscriber> QOTDSubscribers { get; set; }
        public virtual DbSet<QuoteFlag> QuoteFlags { get; set; }
        public virtual DbSet<QuoteFlagType> QuoteFlagTypes { get; set; }
        public virtual DbSet<QuoteHistory> QuoteHistories { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<QuoteTaskHistory> QuoteTaskHistories { get; set; }
        public virtual DbSet<QuoteTaskType> QuoteTaskTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
        public virtual DbSet<ContributionsView> ContributionsViews { get; set; }
        public virtual DbSet<QuotesView> QuotesViews { get; set; }
        public virtual DbSet<SearchReportView> SearchReportViews { get; set; }
    
        [DbFunction("WwfdEntities", "Split")]
        public virtual IQueryable<Split_Result> Split(string s, string sep)
        {
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            var sepParameter = sep != null ?
                new ObjectParameter("sep", sep) :
                new ObjectParameter("sep", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[WwfdEntities].[Split](@s, @sep)", sParameter, sepParameter);
        }
    
        public virtual int AddQOTDSubscriber(string emailAddress)
        {
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddQOTDSubscriber", emailAddressParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> AuthenticateUser(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("AuthenticateUser", emailParameter, passwordParameter);
        }
    
        public virtual int BuildKeywordPhrasesTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BuildKeywordPhrasesTable");
        }
    
        public virtual int CreateRandomQOTD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateRandomQOTD");
        }
    
        public virtual ObjectResult<GetQuoteOfTheDay_Result> GetQuoteOfTheDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetQuoteOfTheDay_Result>("GetQuoteOfTheDay");
        }
    
        public virtual ObjectResult<GetRandomQuote_Result> GetRandomQuote()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRandomQuote_Result>("GetRandomQuote");
        }
    
        public virtual ObjectResult<Nullable<int>> GetRandomQuoteID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetRandomQuoteID");
        }
    
        public virtual ObjectResult<GetStats_Result> GetStats()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStats_Result>("GetStats");
        }
    
        public virtual int GetTopKeywordPhrases()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetTopKeywordPhrases");
        }
    
        public virtual ObjectResult<SearchFounders_Result> SearchFounders(string searchText)
        {
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchFounders_Result>("SearchFounders", searchTextParameter);
        }
    
        public virtual ObjectResult<SearchQuotes_Result> SearchQuotes(string searchText)
        {
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchQuotes_Result>("SearchQuotes", searchTextParameter);
        }
    
        public virtual int SearchQuotesOld(string searchText, Nullable<bool> saveSearch)
        {
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            var saveSearchParameter = saveSearch.HasValue ?
                new ObjectParameter("SaveSearch", saveSearch) :
                new ObjectParameter("SaveSearch", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SearchQuotesOld", searchTextParameter, saveSearchParameter);
        }
    
        public virtual int SetQOTDStatus(Nullable<System.DateTime> quoteDate, Nullable<bool> status)
        {
            var quoteDateParameter = quoteDate.HasValue ?
                new ObjectParameter("QuoteDate", quoteDate) :
                new ObjectParameter("QuoteDate", typeof(System.DateTime));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetQOTDStatus", quoteDateParameter, statusParameter);
        }
    }
}
