//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wwfd.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Founder
    {
        public Founder()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public int FounderID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateBorn { get; set; }
        public Nullable<System.DateTime> DateDied { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
