//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wwfd.Core.Data
{
    using System;
    
    public partial class SearchResult
    {
        public string FullName { get; set; }
        public string QuoteText { get; set; }
        public int QuoteID { get; set; }
        public int FounderID { get; set; }
        public string ReferenceInfo { get; set; }
    }
}
