//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wwfd.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class WwfdEntities : DbContext
    {
        public WwfdEntities()
            : base("name=WwfdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Founder> Founders { get; set; }
        public DbSet<Quote> Quotes { get; set; }
        public DbSet<Search> Searches { get; set; }
        public DbSet<QuotesView> QuotesViews { get; set; }
    
        public virtual ObjectResult<SearchResult> SearchQuotes(string searchText, Nullable<bool> saveSearch)
        {
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            var saveSearchParameter = saveSearch.HasValue ?
                new ObjectParameter("SaveSearch", saveSearch) :
                new ObjectParameter("SaveSearch", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchResult>("SearchQuotes", searchTextParameter, saveSearchParameter);
        }
    }
}
